mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views


app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<list_id>[0-9]+)$', views.list_contents, name='list_contents'),
    #
    url(r'^(?P<question_id>[0-9]+)/question_contents$', views.question_contents, name='question_contents'),
    # ex: /polls/5/results/
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),


   
    
              
]

mysite/polls/models.py
from django.db import models

class List(models.Model):
    def __str__(self):
        return self.list_text
    list_text = models.CharField(max_length=50)
    pub_date = models.DateTimeField('date published')


class Question(models.Model):
    def __str__(self):
        return self.question_text
    lista = models.ForeignKey(List,on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    question_text2 = models.CharField(max_length=500,default='Questao vazia')
    question_text3 = models.CharField(max_length = 50,default = '0')
    image = models.ImageField(upload_to="images")
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

mysite/polls/views.py
from django.http import HttpResponse
from django.template import loader
from django.urls import reverse
from django.shortcuts import get_object_or_404, render



from .models import List,Question,Choice


def index(request):
    list_list = List.objects.order_by('-pub_date')
    context = {
        'list_list': list_list,
    }
    return render(request,'polls/index.html',context)


def list_contents(request, list_id):
    lc = get_object_or_404(List,pk=list_id)
    return render(request, 'polls/list_contents.html', {'lc': lc})
# Leave the rest of the views (detail, results, vote) unchanged
# ...

def question_contents(request,question_id):
    print("lol")
    question = get_object_or_404(Question,pk=question_id)
    #return HttpResponse("You're voting on question %s." % question_id)
    return render(request,'polls/question_contents.html', {'question': question })



def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/question_contents.html', {
            'question': question,
            'error_message': "Você não assinalou uma opção",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/index.html
<!DOCTYPE html>

<html>
    
<head>
    <title>question_contents</title>
    {%load staticfiles%}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel='stylesheet' href="/static/polls/css/bootstrap.min.css">

    <script src="/static/polls/js/bootstrap.js" type="text/javascript"></script>
    <script src="/static/polls/js/quizz.js" type="text/javascript"></script>
    <script src="/static/polls/js/textanimation.js" type="text/javascript"></script>
    <link rel='stylesheet' href="/static/polls/css/front.css">
    
</head>



<span id = "header">
<h1>
  <a href="" class="typewrite" data-period="2000" data-type='[ "Oi, Eu sou o  Professor Laython.", "Você gosta de enigmas?", "Clique num dos tópicos abaixo!", "Depois escolha um enigma." ]'>
    <span class="wrap"></span>
  </a>
</h1>
</span>


<div><img src="http://orig04.deviantart.net/a387/f/2017/049/3/7/ten_years_of_fun_puzzle_solving__by_glitxd-dazhqk9.png" style="width:400px; height:300px;"> </div>



<div id ="topicos">
{% if list_list %}
    <ul>
    {% for tema in list_list %}
        <li><a href="{% url 'polls:list_contents' tema.id %}">{{ tema.list_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No lists are available.</p>
{% endif %}




</div>

</html>

mysite/polls/templates/polls/list_contents.html
<!DOCTYPE html>

<html>
    
<head>
    <title>question_contents</title>
    {%load staticfiles%}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel='stylesheet' href="/static/polls/css/bootstrap.min.css">

    <script src="/static/polls/js/bootstrap.js" type="text/javascript"></script>
    <script src="/static/polls/js/quizz.js" type="text/javascript"></script>
    
    <link rel='stylesheet' href="/static/polls/css/front.css">
    
</head>


<span id = "header">
<h1>
    <span class="wrap">{{ lc.list_text }}</span>
</h1>
</span>


<div><img src="http://orig04.deviantart.net/a387/f/2017/049/3/7/ten_years_of_fun_puzzle_solving__by_glitxd-dazhqk9.png" style="width:400px; height:300px;"> </div>



<div class="container container-table">
    <div class="row vertical-center-row">
        <div class="text-center col-md-4 col-md-offset-4">
<h1></h1>
<ul>
{% for question in lc.question_set.all %}
    <li><a href="{% url 'polls:question_contents' question.id %}">{{ question.question_text }}</a></li>
{% endfor %}
</ul>

</div>
</div>
</div>

</html>

mysite/polls/templates/polls/question_contents.html
<!DOCTYPE html>

<html>
    
<head>
    <title>question_contents</title>
    {%load staticfiles%}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <link rel='stylesheet' href="/static/polls/css/bootstrap.min.css">
    <script src="/static/polls/js/bootstrap.js" type="text/javascript"></script>
    <script src="/static/polls/js/quizz.js" type="text/javascript"></script>
    <link rel='stylesheet' href="/static/polls/css/quest.css">
</head>





<div class="container container-table">
    <div class="row vertical-center-row">
        <div class="text-center col-md-4 col-md-offset-4">
        	<h1 >{{ question.question_text }}</h1>

			{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

			<p id="qtext" =>{{question.question_text2}}</p>
			
			<img src="/static/polls/media/{{question.image.url}}"  style="width:400px;height:300px;">
 			<p> Resposta: <input type="text" name="fname" id="answer"><br></p>
  <button class="btn btn-primary" id ="respond" onclick="setTimeout(function() {
   
responder('{{question.question_text3}}')}, 1000);">Submeter</button>

        	




        </div>


    </div>
</div>



</html>